#!/usr/bin/env bash

service="home-server.service"

# Copy to root services folder
sudo cp $service /etc/systemd/system/

# Reload systemd to include service
sudo systemctl daemon-reload

# Start service on next book
sudo systemctl enable $service

# Start service immediately
sudo systemctl start $service
